<a href="https://colab.research.google.com/github/siva4iov/FlatsPrice_DS_Proj/blob/master/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files
import os

if not os.path.exists("/content/dataset.csv"):
  files.upload()

Saving dataset.csv to dataset.csv

In [46]:
df = pd.read_csv("/content/dataset.csv", delimiter=";")
df.head()

,Балкон или лоджия,Мебель,Адрес,Жилая площадь,Количество комнат,Ремонт,Интернет и ТВ,Цена,Техника,Общая площадь,Площадь кухни,Санузел,Этаж,Оплата по счётчикам,Тип комнат
0,балкон,"кухня, хранение одежды, спальные места","Республика Татарстан, Казань, ул. Разведчика А...",20 м²,1,косметический,"Wi-Fi, телевидение",27 000,"холодильник, плита, стиральная машина, телевизор",39 м²,12 м²,совмещенный,10 из 19,NaN,NaN
1,NaN,NaN,"Республика Татарстан, Казань, Вахитовский райо...",NaN,студия,косметический,NaN,14 000,NaN,18 м²,NaN,совмещенный,9 из 9,включена в плату,NaN
2,"балкон, лоджия","кухня, хранение одежды, спальные места","Республика Татарстан, Казань, ул. Мидхата Була...",NaN,3,евро,NaN,40 000,"кондиционер, холодильник, плита, микроволновк...",105 м²,25 м²,совмещенный,2 из 5,NaN,изолированные
3,NaN,"кухня, хранение одежды, спальные места","Республика Татарстан, Казань, пр-т Альберта Ка...",16 м²,1,евро,NaN,27 000,"кондиционер, холодильник, плита, микроволновк...",32 м²,9 м²,NaN,14 из 23,NaN,NaN
4,балкон,"кухня, хранение одежды, спальные места","Республика Татарстан, Казань, ул. Сибгата Хаки...",13.5 м²,1,евро,NaN,20 000,"кондиционер, холодильник, плита, микроволновк...",45 м²,17.5 м²,совмещенный,5 из 9,NaN,NaN

#Rename columns
First of all, let's rename the columns so that the names would be in дatin

In [47]:
new_names = [
    "Balcony", "Furniture", "Address", "Living_space", "Num_of_rooms", 
 "Renovation", "Internet_tv", "Price", "Appliances", 'Total_area', 
 'Kitchen_area', "Bathroom", "Floor", "Utilities", 'Room_type'
 ]
mapper = {key:value for key, value in zip(df.columns.values, new_names)}

df = df.rename(columns=mapper)
df

,Balcony,Furniture,Address,Living_space,Num_of_rooms,Renovation,Internet_tv,Price,Appliances,Total_area,Kitchen_area,Bathroom,Floor,Utilities,Room_type
0,балкон,"кухня, хранение одежды, спальные места","Республика Татарстан, Казань, ул. Разведчика А...",20 м²,1,косметический,"Wi-Fi, телевидение",27 000,"холодильник, плита, стиральная машина, телевизор",39 м²,12 м²,совмещенный,10 из 19,NaN,NaN
1,NaN,NaN,"Республика Татарстан, Казань, Вахитовский райо...",NaN,студия,косметический,NaN,14 000,NaN,18 м²,NaN,совмещенный,9 из 9,включена в плату,NaN
2,"балкон, лоджия","кухня, хранение одежды, спальные места","Республика Татарстан, Казань, ул. Мидхата Була...",NaN,3,евро,NaN,40 000,"кондиционер, холодильник, плита, микроволновк...",105 м²,25 м²,совмещенный,2 из 5,NaN,изолированные
3,NaN,"кухня, хранение одежды, спальные места","Республика Татарстан, Казань, пр-т Альберта Ка...",16 м²,1,евро,NaN,27 000,"кондиционер, холодильник, плита, микроволновк...",32 м²,9 м²,NaN,14 из 23,NaN,NaN
4,балкон,"кухня, хранение одежды, спальные места","Республика Татарстан, Казань, ул. Сибгата Хаки...",13.5 м²,1,евро,NaN,20 000,"кондиционер, холодильник, плита, микроволновк...",45 м²,17.5 м²,совмещенный,5 из 9,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1645,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#Count None entries
Let's count none values, and all none rows

In [49]:
def count_none():
  for col in df.columns:
    nasum = df[col].isna().sum()
    print(f'{col} - {nasum} none entries')
count_none()
none_rows = np.all(df.isna().values, axis=1)
num_none_rows = none_rows.sum()
print(f'Full none rows - {num_none_rows}')

Balcony - 680 none entries
Furniture - 562 none entries
Address - 44 none entries
Living_space - 751 none entries
Num_of_rooms - 44 none entries
Renovation - 44 none entries
Internet_tv - 828 none entries
Price - 44 none entries
Appliances - 372 none entries
Total_area - 44 none entries
Kitchen_area - 139 none entries
Bathroom - 563 none entries
Floor - 44 none entries
Utilities - 1567 none entries
Room_type - 914 none entries
Full none rows - 44

**As we can see, we have 44 completely none rows.**  
If we get rid of them, then each row will have a price, a total_area etc.

# Let's drop them

In [50]:
df = df[~none_rows]
count_none()

Balcony - 636 none entries
Furniture - 518 none entries
Address - 0 none entries
Living_space - 707 none entries
Num_of_rooms - 0 none entries
Renovation - 0 none entries
Internet_tv - 784 none entries
Price - 0 none entries
Appliances - 328 none entries
Total_area - 0 none entries
Kitchen_area - 95 none entries
Bathroom - 519 none entries
Floor - 0 none entries
Utilities - 1523 none entries
Room_type - 870 none entries

Much better!

# Next step is to cast features to right types

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1606 entries, 0 to 1640
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Balcony       970 non-null    object
 1   Furniture     1088 non-null   object
 2   Address       1606 non-null   object
 3   Living_space  899 non-null    object
 4   Num_of_rooms  1606 non-null   object
 5   Renovation    1606 non-null   object
 6   Internet_tv   822 non-null    object
 7   Price         1606 non-null   object
 8   Appliances    1278 non-null   object
 9   Total_area    1606 non-null   object
 10  Kitchen_area  1511 non-null   object
 11  Bathroom      1087 non-null   object
 12  Floor         1606 non-null   object
 13  Utilities     83 non-null     object
 14  Room_type     736 non-null    object
dtypes: object(15)
memory usage: 200.8+ KB

**Now all features are object type**.     

 I am going to figure out how to remove empty and extra characters and then cast everything to the right types

In [59]:
for col in ["Balcony", "Furniture", "Renovation", "Internet_tv", 
"Bathroom", "Utilities", 'Room_type'
 ]:
 print(f'{col}: {df[col][df[col].notna()].unique()}\n{"*"*50}')

Balcony: [' балкон' ' балкон, лоджия' ' лоджия']
**************************************************
Furniture: [' кухня, хранение одежды, спальные места' ' кухня, спальные места'
 ' спальные места' ' кухня, хранение одежды'
 ' хранение одежды, спальные места' ' кухня']
**************************************************
Renovation: [' косметический' ' евро' ' дизайнерский' ' требует ремонта']
**************************************************
Internet_tv: [' Wi-Fi, телевидение' ' Wi-Fi' ' телевидение' ' Wi-Fi, телевизор'
 ' телевизор']
**************************************************
Bathroom: [' совмещенный' ' раздельный' ' совмещенный, раздельный']
**************************************************
Utilities: [' включена в плату']
**************************************************
Room_type: [' изолированные' ' смежные' ' изолированные, смежные']
**************************************************

Some of this feautures looks like just arrays, so we should consider that.




So is Appliances, but there are bigger arrays, I will demonstrate one:

In [62]:
df["Appliances"][df["Appliances"].notna()].unique()[1]

' кондиционер, холодильник, плита, микроволновка, стиральная машина, водонагреватель, телевизор'